"""empty message

Revision ID: 779789d2e9fe
Revises: e3a7636b01dd
Create Date: 2020-07-08 04:11:03.458227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779789d2e9fe'
down_revision = 'e3a7636b01dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_model', sa.Column('model', sa.String(length=28), nullable=True))
    op.add_column('current_model', sa.Column('transformer', sa.String(length=28), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('current_model', 'transformer')
    op.drop_column('current_model', 'model')
    # ### end Alembic commands ###
