"""Current model

Revision ID: e3a7636b01dd
Revises: 7ca7b2c97019
Create Date: 2020-07-03 00:29:46.542068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a7636b01dd'
down_revision = '7ca7b2c97019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=20), nullable=True),
    sa.Column('model_type', sa.String(length=64), nullable=True),
    sa.Column('model_params', sa.String(length=140), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_current_model_model_id'), 'current_model', ['model_id'], unique=False)
    op.drop_index('ix_model_name', table_name='model')
    op.drop_table('model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=64), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('active IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_name', 'model', ['name'], unique=1)
    op.drop_index(op.f('ix_current_model_model_id'), table_name='current_model')
    op.drop_table('current_model')
    # ### end Alembic commands ###
